[project]
name = "voz-legenda"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "argostranslate>=1.9.6",
    "flet[all]>=0.25.2",
    "pyinstaller>=6.11.1",
    "sounddevice>=0.5.1",
    "vosk==0.3.44",
]
