[project]
name = "voz-legenda"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flet[all]>=0.25.2",
    "sounddevice>=0.5.1",
    "vosk>=0.3.45",
]
